% TemporalAttentionAdjustScripts

% combine runs
rd_combineRunsTemporalAttentionAdjust

% response & errors sequence (does not depend on fit)
rd_plotTemporalAttentionAdjustResponseGroup
rd_plotTemporalAttentionAdjustErrorsGroup
rd_plotTemporalAttentionAdjustBigErrors
rd_fitDOG

% mixture model fit sequence
rd_fitTemporalAttentionAdjustGroup
rd_plotTemporalAttentionAdjustFit 
rd_organizeAdjustFitGroupStats
rd_plotTemporalAttentionAdjustParamTradeoffs

